[tool.poetry]
name = "neural-networks"
version = "0.1.0"
description = ""
authors = ["loganpowell <loganp@tepper.cmu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.4.1.post1"
torch = "^2.2.1"
torchvision = "^0.17.1"
seaborn = "^0.13.2"

[tool.poetry.group.dev.dependencies]
numpy = "^1.26.4"
matplotlib = "^3.8.3"
pandas = "^2.2.1"
ipykernel = "^6.29.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
